import './admin/ajax';
import './admin/beforeunload';
import './admin/confirmable';
import './admin/debounce';
import './admin/modal';
import './admin/slugable';
import './admin/spinner';
import './admin/toast';
import './admin/toggleable';
